import { IconSignupProfile } from "@/assets/Icons";
import { PrimaryBtn } from "@/common/PrimaryBtn";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Input } from "postcss";
import { useEffect, useRef, useState } from "react";
import { IoEyeOff, IoEyeSharp } from "react-icons/io5";
import { MdArrowBack } from "react-icons/md";
export default function Home() {
  const [value, setValue] = useState(null);
  //   const [show, setShow] = useState(false);
  const [passwordShow, setPasswordShow] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 pt-12 flex flex-col gap-14 items-center ">
        <div className="relative w-full flex flex-col items-center gap-4">
          <div className="bg-primary-50 rounded-full w-28 h-28 relative">
            <Image
              alt="profile"
              src={IconSignupProfile}
              className="absolute w-[95%] h-[95%]"
            />
          </div>
          <span className="text-sm">اطلاعات ورود</span>
          <button
            onClick={() => level > 0 && setLevel(level - 1)}
            className="text-2xl absolute top-0 left-0"
          >
            <MdArrowBack />
          </button>
        </div>

        <form className="flex flex-col items-center gap-8 w-full">
          <input
            type={"text"}
            placeholder="نام"
            className="w-full h-12 rounded-4xl focus:border border-gray-50 outline-none p-4 bg-primary-50  text-sm placeholder:text-gray-300 text-gray-900 "
          />
          <input
            type={"text"}
            placeholder="نام خانوادگی"
            className="w-full h-12 rounded-4xl focus:border border-gray-50 outline-none p-4 bg-primary-50  text-sm placeholder:text-gray-300 text-gray-900 "
          />
          <div className="w-full h-12 rounded-4xl bg-primary-50 relative">
            <input
              type={passwordShow ? "text" : "password"}
              placeholder="رمز عبور"
              className="w-full h-12 rounded-4xl focus:border border-gray-50 outline-none p-4 bg-primary-50  text-sm placeholder:text-gray-300 text-gray-900 "
            />
            <button
              className="text-gray-400 absolute md:text-2xl text-lg top-4 left-4"
              onClick={() => setPasswordShow(!passwordShow)}
              type={"button"}
            >
              {!passwordShow ? <IoEyeSharp /> : <IoEyeOff />}
            </button>
          </div>
          <div className="w-full h-12">
            <PrimaryBtn text="ثبت" onClick={() => setLevel(1)} />
          </div>
        </form>
      </main>
    </>
  );
}
