import { IconSignupProfile } from "@/assets/Icons";
import { PrimaryBtn } from "@/common/PrimaryBtn";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Input } from "postcss";
import { useEffect, useRef, useState } from "react";
import { MdArrowBack } from "react-icons/md";
export default function Home() {
  const [level, setLevel] = useState(0);
  const [value, setValue] = useState(null);
  const inputRef1 = useRef(null);
  const inputRef2 = useRef(null);
  const inputRef3 = useRef(null);
  const inputRef4 = useRef(null);
  useEffect(() => {
    if (level === 1) {
      inputRef1.current.focus();
    }
  }, [level]);
  useEffect(() => {
    if (value && value[1] && value[2] && value[3] && value[4]) {
      setLevel(2);
    }
  }, [value]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 pt-12 flex flex-col gap-14 items-center ">
        <div className="relative w-full flex flex-col items-center gap-4">
          <div className="bg-primary-50 rounded-full w-28 h-28 relative">
            <Image
              alt="profile"
              src={IconSignupProfile}
              className="absolute w-[95%] h-[95%]"
            />
          </div>
          <span className="text-sm">
            {level === 0
              ? "ثبت شماره موبایل"
              : level === 1
              ? "تایید شماره تلفن"
              : "اطلاعات کاربری"}
          </span>
          <button
            onClick={() => level > 0 && setLevel(level - 1)}
            className="text-2xl absolute top-0 left-0"
          >
            <MdArrowBack />
          </button>
        </div>
        {level === 0 ? (
          <form className="flex flex-col items-center gap-8">
            <div className="w-full flex flex-col items-center gap-3 ">
              <div className="w-full flex flex-row items-center justify-between h-12 p-1 rounded-4xl bg-primary-50">
                <input
                  type={"tel"}
                  maxLength={11}
                  className=" w-full rounded-4xl outline-none p-2 h-full bg-primary-50 "
                />
                <div className="w-[20%] h-full flex items-center justify-center text-sm text-white rounded-l-4xl bg-primary-900">
                  +98
                </div>
              </div>
              <p className="text-xs">
                به منظور تکمیل روند ثبت یک کد برای شما ارسال می گردد
              </p>
            </div>
            <div className="w-full h-12">
              <PrimaryBtn text="ثبت" onClick={() => setLevel(1)} />
            </div>
          </form>
        ) : level === 1 ? (
          <form className="flex flex-col items-start gap-6">
            <span className="text-[10px]">
              لطفا کد ارسال شده را وارد نمایید
            </span>
            <div className="flex flex-row items-center gap-3">
              <div className="flex flex-col items-center gap-1 w-14 h-14">
                <input
                  type="tel"
                  max={1}
                  maxLength="1"
                  ref={inputRef4}
                  onKeyUp={(e) => {
                    setValue({ ...value, 4: e.target.value });
                  }}
                  className="w-full text-center outline-none p-1 bg-primary-50 h-full rounded-lg "
                />
                <div className="h-1 w-full bg-primary-50 rounded-4xl"></div>
              </div>
              <div className="flex flex-col items-center gap-1 w-14 h-14">
                <input
                  type="tel"
                  max={1}
                  maxLength="1"
                  ref={inputRef3}
                  onKeyUp={(e) => {
                    inputRef4.current.focus();
                    setValue({ ...value, 3: e.target.value });
                  }}
                  className="w-full text-center  outline-none p-1 bg-primary-50 h-full rounded-lg "
                />
                <div className="h-1 w-full bg-primary-50 rounded-4xl"></div>
              </div>
              <div className="flex flex-col items-center gap-1 w-14 h-14">
                <input
                  type="tel"
                  max={1}
                  ref={inputRef2}
                  maxLength="1"
                  onKeyUp={(e) => {
                    inputRef3.current.focus();
                    setValue({ ...value, 2: e.target.value });
                  }}
                  className="w-full text-center  outline-none p-1 bg-primary-50 h-full rounded-lg "
                />
                <div className="h-1 w-full bg-primary-50 rounded-4xl"></div>
              </div>
              <div className="flex flex-col items-center gap-1 w-14 h-14">
                <input
                  type="tel"
                  max={1}
                  maxLength="1"
                  ref={inputRef1}
                  onKeyUp={(e) => {
                    e.target.value && inputRef2.current.focus();
                    setValue({ 1: e.target.value });
                  }}
                  className="w-full text-center  outline-none p-1 bg-primary-50 h-full rounded-lg "
                />
                <div className="h-1 w-full bg-primary-50 rounded-4xl"></div>
              </div>
            </div>
            <div className="w-full -mt-4 flex items-center justify-end">
              <Link href={"#"} className="text-[10px] text-primary-900">
                دریافت مجدد کد
              </Link>
            </div>
          </form>
        ) : (
          <form className="flex flex-col items-center gap-8 w-full">
            <input
              type={"text"}
              placeholder="نام"
              className="w-full h-12 rounded-4xl focus:border border-gray-50 outline-none p-4 bg-primary-50  text-sm placeholder:text-gray-300 text-gray-900 "
            />
            <input
              type={"text"}
              placeholder="نام خانوادگی"
              className="w-full h-12 rounded-4xl focus:border border-gray-50 outline-none p-4 bg-primary-50  text-sm placeholder:text-gray-300 text-gray-900 "
            />
            <div className="w-full h-12">
              <PrimaryBtn text="ثبت" onClick={() => setLevel(1)} />
            </div>
          </form>
        )}
      </main>
    </>
  );
}
